# https://dev.to/typescripttv/getting-started-with-github-actions-and-workflows-2ki2

name: 'CI'

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # https://github.com/tj-actions/changed-files
  changed:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/**
            **.js
            **.mjs
            tsconfig.json
            pnpm-lock.yaml
  lint:
    name: 'Lint & Typecheck'
    needs: changed
    if: needs.changed.outputs.any_changed == 'true'
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # Assume PRs are less than 50 commits

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
